"""
Pydantic schemas for Root Cause Analysis (RCA) Reports generated by ObservaSage.
"""

from enum import Enum
from typing import List, Literal, Optional
from pydantic import BaseModel, Field, model_validator


class FailureCategory(str, Enum):
    EC_1_OOM = "EC-1: OOM / Resource Exhaustion"
    EC_2_LATENCY = "EC-2: Flaky / Intermittent Latency"
    EC_3_CASCADE = "EC-3: Cascading Service Crash"
    EC_4_SILENT = "EC-4: Silent Data Corruption"
    EC_5_INFRA = "EC-5: Infrastructure Drift / Network Partition"
    CODE_BUG = "CODE_BUG: Application Exception / Logic Error"
    UNKNOWN = "UNKNOWN: Unclassified Failure"


class EvidenceTriangulation(BaseModel):
    primary_signal: Literal["LOGS", "METRICS", "TRACES", "FUSION"]
    logs_insight: Optional[str] = Field(default=None, description="What logs revealed (novel templates / stack traces)")
    metrics_insight: Optional[str] = Field(default=None, description="What metrics revealed (Z-score anomalies / memory slopes)")
    traces_insight: Optional[str] = Field(default=None, description="What traces revealed (DFS leaf culprit span / error codes)")
    triangulation_reasoning: str = Field(description="How multi-signal correlation arrived at this conclusion")


class RemediationStep(BaseModel):
    action: str
    target_service: str
    command_or_config: Optional[str] = None
    expected_impact: str


class RCAReport(BaseModel):
    run_id: str
    scenario: str
    root_cause_service: str
    culprit_services: List[str] = Field(
        default_factory=list,
        description="Ranked top suspected culprit services (Top-k candidates)",
    )
    failure_category: FailureCategory
    confidence_score: float = Field(ge=0.0, le=1.0, description="Confidence between 0.0 and 1.0")
    root_cause_summary: str = Field(description="Precise technical root cause diagnosis")
    evidence_triangulation: EvidenceTriangulation
    culprit_trace_id: Optional[str] = None
    culprit_span_id: Optional[str] = None
    remediation_steps: List[RemediationStep] = Field(default_factory=list)
    prompt_tokens_used: int = 0
    total_tokens_used: int = 0

    @model_validator(mode="after")
    def sync_culprit_services(self) -> "RCAReport":
        if not self.culprit_services and self.root_cause_service:
            self.culprit_services = [self.root_cause_service]
        elif self.culprit_services and not self.root_cause_service:
            self.root_cause_service = self.culprit_services[0]
        return self
